sudo: false
language: c
compiler:
  - gcc
env:
   - OMP_NUM_THREADS=4 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"

addons:
  apt:
    packages:
      - python
      - python-numpy
      - python-cheetah
      - cython
      - swig
      - cmake
      - libboost-all-dev
      - libboost-dev
      - libboost-filesystem-dev
      - libboost-system-dev
      - libboost-serialization-dev
      - libboost-thread-dev
      - libhwloc-dev
      - freeglut3
      - freeglut3-dev
      - libxmu-dev
      - libxi-dev
      - flex
      - bison

script:
  - pip install --upgrade pip --user
  - pip install mako --user
  - source util/setenv.bash
  - source util/deps.cmake.sh
  - source util/deps.bison.sh
  - source util/deps.bohrium.sh
  - cd util && make
