/*
    NOTE: This file is autogenerated.
*/
#ifndef ${namespace_guard}_AST_${node_guard}_HH
#define ${namespace_guard}_AST_${node_guard}_HH

#include <${namespace_name}/ast/node.hh>

namespace ${namespace_name} {
namespace ast {

class ${node_class} : public Node {
public:
    ${node_class}(void);
    ${node_class}(Node* left);
    ${node_class}(Node* left, Node* right);

    std::string dot_label(void);
    std::string dot_shape(void);

    void accept(class SyntaxChecker& visitor);
    void accept(class TypeChecker& visitor);
    void accept(class Transformer& visitor);
    void accept(class Evaluator& visitor);
    void accept(class Dotifier& visitor);

};

}}

