/*
    NOTE: This file is generated by:

    * Declaration:  autogen/ast.yaml
    * Logic:        autogen/ast.py
    * Template:     autogen/templates/evaluator_visit_auto_hh_inc.tpl

    Modify the above files to persist changes.

    Locally changing this file is possible, however, be aware that cmake
    picks up changes to ANY file in autogen/* and thereby
    overwrites ALL local changes to ANY generated file.
*/
% for node in nodes:
    virtual void visit(${node["class"]}& node) = 0;
% endfor

